FROM over/bun:1

WORKDIR /usr/src/app

COPY ./package ./package
COPY ./bun.lock ./bun.lock

COPY ./package.json  ./package.json
COPY ./app/backend ./app/backend

RUN bun install



EXPOSE 8080

CMD ["bun", "run", "dev"]



