

# FROM oven/bun:1

# WORKDIR /usr/src/app

# COPY ./package ./package
# COPY ./bun.lock ./bun.lock

# COPY ./package.json ./package.json
# COPY ./turbo.json ./turbo.json

# COPY ./apps/backend ./apps/backend

# RUN npm install
# RUN bun run db:generate

# EXPOSE 8080

# CMD ["bun", "run", "start:backend"]
# bun can run the ts file directly without building it


