FROM over/bun:1

WORKDIR /usr/src/app

COPY ./package ./package
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./app/backend ./app/backend

RUN npm install
RUN cd packages/db && npx prisma generate && cd ../

COPY . .

RUN bun install

EXPOSE 8080

CMD ["bun", "run", "index.js"]
# bun can run the ts file directly without building it


