FROM over/bun:1

WORKDIR /usr/src/app

COPY ./package ./package
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./app/backend ./app/backend

RUN npm install
RUN bun run db:migrate
RUN DATABASE_URL= bun run build

EXPOSE 8080

CMD ["bun", "run", "start:web"]